# Generated by Django 3.2.5 on 2021-07-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='contato',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='num',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='rua',
        ),
    ]
