# Generated by Django 3.2.5 on 2021-07-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20210710_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='contato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contatos.contato'),
            preserve_default=False,
        ),
    ]
